###################################################
# BUILT-IN CONFIGURATION OPTOINS                  #
# https://gohugo.io/getting-started/configuration #
###################################################

baseURL = "" # website root path
disqusShortname = ""                      # disqus shortcode
enableGitInfo = false                     # retrieve last modified date from git commits
enableRobotsTXT = true                    # /robots.txt
googleAnalytics = ""                      # google analytics id
hasCJKLanguage = false                     # Chinese/Japanese/Korean
languageCode = "en"                       # content language
paginate = 6                              # number of posts each page
rssLimit = 10                             # maximum items in rss feeds
theme = "hugo-theme-texify"               # theme directory name
title = "Test web site"                   # website title

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

[author]
email = "me@example.com" # your email
name = "Test author"          # your name

# https://gohugo.io/getting-started/configuration-markup
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark.renderer]
unsafe = true # enable html in markdown
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/

# https://gohugo.io/content-management/menus/
[[menu.main]]
identifier = "posts" # section id
name = "Index"       # section display title
url = "/"           # path to the section
weight = 1          # order of sections
[[menu.main]]
identifier = "archives"
name = "Archives"
url = "/post/"
weight = 2

# https://gohugo.io/content-management/taxonomies#configure-taxonomies
[taxonomies]
series = "series" # see https://gohugo.io/templates/internal/#open-graph
tags = "tags"


########################
# TEXIFY THEME OPTIONS #
########################

[params]
description = "an example site for hugo theme TeXify" # website description
favicon = "favicon.ico" # path to website icon, relative to ./static
footnote = """
E-Mail: <a class=link href="mailto:me@example.com">me@example.com</a> | 
<a class=link href="/index.xml">RSS</a> |
<a class=link href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>
""" # notes in the website footer
keywords = ["nature"] # website keywords

customCSS = []            # path to custom css files, relative to ./static
customJS = []             # path to custom js files, relative to ./static
dateFormat = "02-01-2006" # date format, see https://gohugo.io/functions/format/
fullTextRSS = true        # output full-text (instead of only summary) rss
emphasisWithDots = false   # use dots to emphasize chinese texts, see https://zh.wikipedia.org/wiki/%E7%9D%80%E9%87%8D%E5%8F%B7
since = "2023"            # website created year
toc = false               # whether to enable table of contents in posts

# https://giscus.app
[params.giscus]
enable = false # whether to enable giscus
# paste giscus' <script></script> configuration between the triple quotes
script = """
"""

[params.math]
enable = false # whether to enable math typesetting
use = "katex"  # katex or mathjax

[params.outdated]
enable = false # whether to display warnings for outdated posts
limit = 1000   # days between last modified time and outdated time
# warning to be displayed
warning = "⚠️ It has been <i>%d</i> days since the last update, the content of the article may be outdated."

# https://utteranc.es
[params.utterances]
enable = false # whether to enable utterances
# paste utterances' <script></script> configuration between the triple quotes
script = """
"""
