##############################

baseURL = "http://example.org/"
#languageCode = "en-us"
languageCode = "en"                       # content language
title = "My New Hugo Site"
theme = "mini"

##############################
